name: E2E Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: 18
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install backend dependencies
      run: |
        cd backend
        pip install .
        pip install pytest pytest-asyncio
        
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci
        
    - name: Install Playwright Browsers
      run: |
        cd frontend
        npx playwright install --with-deps
        
    - name: Start backend server
      run: |
        cd backend
        export GEMINI_API_KEY=test_key
        export OPENAI_API_KEY=test_key
        python -m uvicorn src.routers.assistant:app --host 0.0.0.0 --port 2024 &
        sleep 10
        
    - name: Start frontend server
      run: |
        cd frontend
        npm run dev &
        sleep 5
        
    - name: Run Playwright tests
      run: |
        cd frontend
        npx playwright test
        
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: frontend/playwright-report/
        retention-days: 30